### ISSUE TITLE
createEnv

### ISSUE THREAD

**Issue by doowb** [node-base/base-runner#1]
I was attempting to load helpers from my local project by using `package.json` and was getting an error.

I changed [this line](https://github.com/jonschlinkert/base-runner/blob/master/index.js#L471) from:

```js
var env = createEnv(fp, opts.cwd, opts);
```

to

```js
var env = createEnv(fp, opts.cwd, new utils.resolver.Resolver.User(opts));
```

I'm not sure if this is the correct approach or if there should be other options passed in, but it seemed to work locally. (I also had to fix a bug in `load-helpers` but that's been published).

If this seems correct, I'll make the change.

**Comment by jonschlinkert** [comment]
Don't push anything up here just yet, but I might use that locally. I'm refactoring some of the resolve-modules stuff. I think I have a way to simplify the resolver and runner stuff quite a bit. 

Basically here is what I'm thinking. Currently, an `env` is created for each matching filepath, which means that `env.user`, `env.config` and `env.module` are created for each match. This isn't really ideal though. 

Here is what I think should happen instead (in `resolve-modules`):

- resolve the user's `cwd` **once**, before any pattern matching.
- resolve the global "fallback" module **once**, before any pattern matching.
- expose a method for getting the "main" `config` to use. By analogy, this would be a `gulpfile.js` or an `assemblefile.js` etc.
- expose a method for getting the `module` to use for a given `config`. It would try to use a local module, and if not available, will fallback to the initial "fallback" global module.
- expose a method for getting the "primary" module. to be used for caching other instances (instead of doing this in `base-runner`). This method would just use the previously-mentioned method to get the initial module for the user's config. 

As an alternative to the last bullet, we could just simply always use an instance of the global module to cache all other instances. It seems like there was a reason we didn't do that initially (e.g. we need to ensure that all settings are created in the context of the user's environment), but I don't remember.

@doowb thoughts?

**Comment by doowb** [comment]
I like all the bullet points. Makes it more explicit as to what we expect to be loaded. 

I think a combination of the last bullet and the last paragraph would work because I think in verb and update you always want a global instance that's different than one a user might have in their local file. In assemble and generate I can see the user's local instance being the parent. 

I think giving to option to the app when it uses base resolve is a good way to do it.

**Comment by jonschlinkert** [comment]
> I think giving to option to the app when it uses base resolve is a good way to do it.

Good idea. we could just expose a method that is used for resolving that first instance. Then require the instance to be passed to `resolve` or something. I'll play around with it a bit. I think we need to get this right, it's making everything else complicated

**Comment by jonschlinkert** [comment]
closing since this refers to an old version of this project
